# Copyright (C) 2021 Abigail Mabe - All Rights Reserved
# You may use, distribute and modify this code under the terms 
# of the license.
#
# You should have received a copy of the license with this file.
# If not, please email <mabe.abby.a@gmail.com>
# 
# Runs the tests.
#
 

name: Flutter_Tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
